### ISSUE TITLE
Removing GC Considerations

### ISSUE THREAD

**Issue by johnjiabinzhang** [microvm/rpython-mu#4]
LLTS distinguishes 'raw' (non-GCed) and 'gc' types.
This distinction is not hugely important, it only kicks in testing and reasoning about inlined structures.
For simplicity, such distinction can be removed, to present a clean and simpler type system, demonstrating that by setting the target platform to Mu, one does not need to worry about the problem of GC.

Here are some thoughts with regard to removing GC.
- to remove 'gc_kind', all things should be treated as if gc_kind='gc'.
- llarena.py module is not needed at all.
- mu(ll)type.malloc/free are used mainly in tests, interpreter (simulator), and prebuilt types and objects. They are not to be confused with op_malloc and op_free.
- Not sure who cares about RuntimeTypeInfo (maybe GCs?), keep it for now.

**Comment by eliotmoss** [comment]
I observe that if we use rpython to help implement components,
particularly the GC, then we DO need non-gc types, not unlike
what lcc currently does (all lcc types are non-gc, since it
is implementing a C universe).

Regards -- Eliot
